---
- name: Install midonet_cluster server
  hosts: midonet_cluster_all
  max_fail_percentage: 0
  user: root
  pre_tasks:
    - name: Use the lxc-openstack aa profile
      lxc_container:
        name: "{{ container_name }}"
        container_config:
          - "lxc.aa_profile=lxc-openstack"
      delegate_to: "{{ physical_host }}"
      when: not is_metal | bool
      register: container_config
      tags:
        - lxc-aa-profile
    - name: Wait for container ssh
      wait_for:
        port: "22"
        delay: "{{ ssh_delay }}"
        search_regex: "OpenSSH"
        host: "{{ ansible_ssh_host }}"
      delegate_to: "{{ physical_host }}"
      when: container_config is defined and container_config | changed
      register: ssh_wait_check
      until: ssh_wait_check | success
      retries: 3
      tags:
        - ssh-wait
  roles:
    - role: "pip_lock_down"
      when: "(groups['repo_all'] | length) >= 1"
    - role: "midonet_repos"
      midonet_version: current
    - role: "midonet_cluster"
      zookeeper_hosts: '{{ groups["zookeeper_all"] }}'
      cassandra_hosts: '{{ groups["cassandra_all"] }}'
      midonet_password: '{{ midonet_api_password }}'
      keystone_username: "{{ keystone_admin_user_name }}"
      keystone_password: "{{ keystone_auth_admin_password }}"
      keystone_project: "{{ keystone_admin_tenant_name }}"
      keystone_token: "{{ keystone_auth_admin_token }}"
      keystone_host: "{{ internal_lb_vip_address }}"
      keystone_port: "{{ keystone_admin_port }}"
      tags:
        - "midonet_cluster-server"
        - "upgrade-midonet_cluster-server"
  vars:
    ansible_hostname: "{{ container_name }}"
    ansible_ssh_host: "{{ container_address }}"
    is_metal: "{{ properties.is_metal|default(false) }}"
